language: ruby
script: rake ci 
rvm:
  - 2.1.1
  - 2.0.0
  - 1.9.3
#  - ruby-head
  - jruby-19mode # JRuby in 1.9 mode
  - jruby-head
notifications:
  email:
    - ndushay@stanford.edu
    - cbeer@stanford.edu

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
